#!/bin/bash

# vérifications du nombre de paramètre si il n'y a pas 1 paramètre le programme s'arrète après avoir envoyé un message dans le terminal
if [ $# -ne 1 ]
then
   echo "Vous devez entrer un argument : stop, start ou restart"
   exit
fi

pid=$(head -1 /var/run/myweb.pid)

case $1 in
"stop")
   top -b -n 1 > tmp.txt
   nbLignes=$(grep -c $pid tmp.txt)
   if [ $nbLignes -eq 0 ]
   then
   	echo "Vous devez d'abord allumer le serveur avant de l'éteindre"
   else
   	kill -9 $pid
   	echo "Le serveur à été arrêté"
   fi;;

"start")
   top -b -n 1 > tmp.txt
   nbLignes=$(grep -c $pid tmp.txt)
   if [ $nbLignes -ne 0 ]
   then
   	echo "Vous devez d'abord éteindre le serveur avant de l'allumer"
   else
   	java /bin/myweb/ServerHTTP.java&
   	nouveauPid=$! 
   	echo $nouveauPid > /var/run/myweb.pid
   	echo "Le serveur à été allumé"
   fi;;

"restart")
   top -b -n 1 > tmp.txt
   nbLignes=$(grep -c $pid tmp.txt)
   if [ $nbLignes -eq 0 ]
   then
   	echo "Vous devez d'abord allumer le serveur avant de le redémarrer"
   else
   	kill -9 $pid
   	java /bin/myweb/ServerHTTP.java&
   	nouveauPid=$! 
   	echo $nouveauPid > /var/run/myweb.pid
   	echo "Le serveur à redémarrer"
   fi;;
esac

